# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, help_text='Foreign key to author(author id)', on_delete=django.db.models.deletion.CASCADE, related_name='author', to='book.Author'),
            preserve_default=False,
        ),
    ]
