# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-24 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170624_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='book',
            field=models.ForeignKey(help_text='Foreign key to book(book id)', on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book.Book'),
        ),
    ]
