# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-26 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20170624_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Foreign key to author(author id)', on_delete=django.db.models.deletion.CASCADE, related_name='author', to='author.Author'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
