# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-26 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20170626_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='book',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
